
export const DEFINE_ROTATION_ROLES = 'DEFINE_ROTATION_ROLES';


// Controls
export const SET_CONTROLS_LEVEL = 'SET_CONTROLS_LEVEL';

// Formations
export const SET_FORMATION = 'SET_FORMATION';
export const SET_ROTATION_BASE = 'SET_ROTATION_BASE';

export const TRANSITION_TO_ATTACK = 'TRANSITION_TO_ATTACK';