export const TRANSITION_TO_BASE_DEFENSE = 'TRANSITION_TO_BASE_DEFENSE';
export const TRANSITION_TO_ATTACK = 'TRANSITION_TO_ATTACK';
export const DEFINE_ROTATION_ROLES = 'DEFINE_ROTATION_ROLES';
export const SET_ROTATION_BASE = 'SET_ROTATION_BASE';

export const SET_CONTROLS_STATE = 'SET_CONTROLS_STATE';